### ISSUE TITLE
Test Issue -- ignore

### ISSUE THREAD

**Issue by amnuxoll** [amnuxoll/AI-Research#1]
I am writing a description of the issue here.  Whee!

**Comment by amnuxoll** [comment]
I am now replying to my own issue.  Are we having fun yet.  I wonder if Will is getting spam.  (Sorry Will if you are.)

**Comment by kirklandspector** [comment]
Hey Nuxoll!
How's it going? Haven't heard from you in a while. Looks like you're
tinkering with the AI again ;)
Hope all is well,
Kirkland

**Comment by amnuxoll** [comment]
Ha!  It looks like I spammed everybody.  Sorry. :3 

It's nifty to hear from you!  Yes, of course still doing research.  We still talk about the "SUS" and the LMS" :)

**Comment by kirklandspector** [comment]
That's awesome to hear! I can't believe Chandler and I were working on it
four years ago now! That was a fun project. I'm not sure how applicable
you're advice will be but I've been gearing up to move out of San Francisco
this year. My two top cities are Montreal and Melbourne, do you know much
about them? I know you were out in New Zealand for a while teaching and
thought maybe you could advise me on Melbourne? Any help is appreciated!
Thanks
Kirk

**Comment by goolkasi18** [comment]
I'll take the apology. Invite me out next time there's a presentation on the AI and I'll be there!
